### ISSUE TITLE
Building CSR from vectors

### ISSUE THREAD

**Issue by jemorlanes** [david-cortes/MatrixExtra#10]
Hi David!

Thank you for developing this package! I have a question. I have at my disposal the 3 vectors used to build a CSR matrix. These vectors i am retrieving by accessing different layers of a `.h5` file. Some example vectors:
```
values <- c(10, 20, 30, 40, 50)
col_indices <- c(0, 1, 0, 2, 3) + 1
row_ptr <- c(0, 1, 2, 4, 5) + 1
```
In my real data, the `col_indices` and `row_ptr` differ in an order of magnitude in length, so I cannot create a sparse matrix and then use `as(, "RsparseMatrix")` to create my CSR matrix.

Is there a way for me to input these vectors to create an object of class `RsparseMatrix `?

I want to turn my CSR vectors to a COO matrix.

Thank you for your time!

**Comment by david-cortes** [comment]
You can use [Matrix::sparseMatrix](https://www.rdocumentation.org/packages/Matrix/versions/1.7-1/topics/sparseMatrix) or S4 "new" on the classes from `Matrix`.
