### ISSUE TITLE
Installation failure: matmul.cpp:137:41: error: ‘ldc’ is predetermined ‘shared’ for ‘shared’  /  private(write_ptr, temp_arr)

### ISSUE THREAD

**Issue by dwinsemius** [david-cortes/MatrixExtra#3]
First tried to install MatrixExtra from within RSudio on a newly updated R. Started by reinstalling all the Imports packages without problems.  Then went to Terminal:

After $R CMD INSTALL ~/MatrixExtra_0.1.9.tar.gz on an Ubuntu 18.04 box I get:

david@davids:/usr/lib/R$ R CMD INSTALL ~/MatrixExtra_0.1.9.tar.gz
* installing to library ‘/home/david/R/x86_64-pc-linux-gnu-library/3.5.1’
* installing *source* package ‘MatrixExtra’ ...
** package ‘MatrixExtra’ successfully unpacked and MD5 sums checked
** using staged installation
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DUSE_ROBINMAP -DHAS_LD=1 -DSUPPORTS_RESTRICT=1 -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/Rcpp/include' -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/float/include'   -fopenmp -fno-trapping-math -fno-math-errno -fvisibility=hidden -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J7pprH/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -Wno-ignored-attributes -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DUSE_ROBINMAP -DHAS_LD=1 -DSUPPORTS_RESTRICT=1 -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/Rcpp/include' -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/float/include'   -fopenmp -fno-trapping-math -fno-math-errno -fvisibility=hidden -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J7pprH/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -Wno-ignored-attributes -c assignment.cpp -o assignment.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DUSE_ROBINMAP -DHAS_LD=1 -DSUPPORTS_RESTRICT=1 -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/Rcpp/include' -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/float/include'   -fopenmp -fno-trapping-math -fno-math-errno -fvisibility=hidden -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J7pprH/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -Wno-ignored-attributes -c cbind.cpp -o cbind.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DUSE_ROBINMAP -DHAS_LD=1 -DSUPPORTS_RESTRICT=1 -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/Rcpp/include' -I'/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/float/include'   -fopenmp -fno-trapping-math -fno-math-errno -fvisibility=hidden -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J7pprH/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -Wno-ignored-attributes -c matmul.cpp -o matmul.o
matmul.cpp: In function ‘void gemm_csr_drm_as_dcm(int, int, const int*, const int*, const double*, const real_t*, size_t, real_t*, int, int)’:
matmul.cpp:137:41: error: ‘ldc’ is predetermined ‘shared’ for ‘shared’
             private(write_ptr, temp_arr)
                                         ^
/usr/lib/R/etc/Makeconf:177: recipe for target 'matmul.o' failed
make: *** [matmul.o] Error 1
ERROR: compilation failed for package ‘MatrixExtra’
* removing ‘/home/david/R/x86_64-pc-linux-gnu-library/3.5.1/MatrixExtra’

david@davids:/usr/lib/R$ R --version
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by david-cortes** [comment]
Thanks for the bug report. This is already solved in the master branch and the new version should get accepted at CRAN soon. In the meantime, you can install it like this:
```r
remotes::install_github("david-cortes/MatrixExtra")
```
