### ISSUE TITLE
crossprod(dgRMatrix, denseVector), Error in .local(x, y, ...) : unused argument (boolArith = NA)

### ISSUE THREAD

**Issue by lovestat** [david-cortes/MatrixExtra#7]
On Windows 10 platform, the title error will happen. Could you please check a bit? Thanks. Below is the data and code I used,

```
y.url <- "https://raw.githubusercontent.com/lovestat/speedglm-test/main/y_vanderbilt.rds"
x.url <- "https://raw.githubusercontent.com/lovestat/speedglm-test/main/x.dgR.rds"
download.file(y.url,"y.rds", method="curl")
download.file(x.url,"x.rds", method="curl")
y <- readRDS("y.rds")
x <- readRDS("x.rds")
class(y)
class(x)
Xy <- MatrixExtra::crossprod(x, y)
```

**Comment by david-cortes** [comment]
This error is from the package `Matrix` and was solved recently in their development version. Not sure if it's updated on CRAN yet.

Nevertheless, if you are seeing this error, it means that the operation is not being done by package `MatrixExtra` - you need to load the library beforehand with `library(MatrixExtra)`. If you want to call the method directly with `::`, I guess you'd have to pick one of those long names with underscores.

**Comment by lovestat** [comment]
Thanks a lot, I will check the development version of `Matrix`.
