### ISSUE TITLE
rbind() cannot be used with do.call()

### ISSUE THREAD

**Issue by rcastelo** [david-cortes/MatrixExtra#9]
Hi,

I want to iterate through the rows of a large sparse matrix, and found the subsetting-row operator of the MatrixExtra package very handy because it provides a `sparseVector` object for each row. The result of that iteration is again a `sparseVector` for each row, which I would like to row-bind back into a sparseMatrix. The problem is that, I would do that with a `do.call()`, but it chokes when more than two elements in the argument list are given:

```
library(Matrix)
library(MatrixExtra)

row_ix <- c(1, 1, 2, 3)
col_ix <- c(1, 3, 3, 2)
values <- c(1, 2, 3, 4)
X <- Matrix::sparseMatrix(
     i=row_ix, j=col_ix, x=values,
     index1=TRUE, repr="T"
 )
do.call(rbind, list(X[1, ], X[2, ]))
Sparse CSR matrix (class 'dgRMatrix')
Dimensions: 2 x 3
(3 entries, 50.00% full)
do.call(rbind, list(X[1, ], X[2, ], X[3, ]))
Error in rbind2(..1) : no method for coercing this S4 class to a v
```

**Comment by david-cortes** [comment]
You can use `MatrixExtra::rbind_csr`:
```r
do.call(rbind_csr, list(X[1, ], X[2, ], X[3, ]))
```
```
Sparse CSR matrix (class 'dgRMatrix')
Dimensions: 3 x 3
(4 entries, 44.44% full)
```

As for the lack of `rbind` with `sparseVector` objects, perhaps you could bring that up with the `Matrix` authors.
